apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-db
  name: inventory-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: inventory-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: inventory-db
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: inventory-db
          image: ghcr.io/01-edu/content-postgres-db:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: INVENTORY_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: INVENTORY_DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: INVENTORY_DB_NAME
          livenessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 5
            periodSeconds: 3
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 5
            periodSeconds: 3
            timeoutSeconds: 1
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: inventory-database
      restartPolicy: Always
      volumes:
        - name: inventory-database
          persistentVolumeClaim:
            claimName: inventory-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: inventory-database
  name: inventory-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
